#!/bin/sh -x

#
# Installation script for assemblyseqload
#
# 1) cp ensembl_assemblyseqload.config.default ensembl_assemblyseqload.config
# 2) cp ncbi_assemblyseqload.config.default ncbi_assemblyseqload.config
# 3) cp assembly_common.config.default assembly_common.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config file names
ENSEMBL_CONFIG=ensembl_assemblyseqload.config
NCBI_CONFIG=ncbi_assemblyseqload.config 
VEGA_CONFIG=vega_assemblyseqload.config
COMMON_CONFIG=assembly_common.config

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBL_CONFIG} ]
then
    echo "Source ${ENSEMBL_CONFIG}"
    . ${ENSEMBL_CONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBL_CONFIG}"
    installFailed
fi

# Make sure common config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
echo "DEV=${DEV}"
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for ensembl seqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# now do ncbi seqload
# 

# Make sure ncbi config file exists and source it
if [ -r ${NCBI_CONFIG} ]
then
    echo "Source ${NCBI_CONFIG}"
    . ${NCBI_CONFIG}
else
    echo "Cannot source configuration file: ${NCBI_CONFIG}"
    installFailed
fi

# source common config again
. ${COMMON_CONFIG}

#
# run DLAInstall for  ncbi seqload
#
${DLAINSTALL} ${DEV}

#
# now do vega seqload
# 

# Make sure vega config file exists and source it
if [ -r ${VEGA_CONFIG} ]
then
    echo "Source ${VEGA_CONFIG}"
    . ${VEGA_CONFIG}
else
    echo "Cannot source configuration file: ${VEGA_CONFIG}"
    installFailed
fi

# source common config again
. ${COMMON_CONFIG}

#
# run DLAInstall for vega seqload
#
${DLAINSTALL} ${DEV}
