#!/bin/sh

#
# Installation script for assemblyseqload
#
# 1) cp ensembl_assemblyseqload.config.default ensembl_assemblyseqload.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config file names
ENSEMBL_CONFIG=ensembl_assemblyseqload.config
ENSEMBLREG_CONFIG=ensemblreg_assemblyseqload.config
NCBI_CONFIG=ncbi_assemblyseqload.config 
MGP_CONFIG=mgp_assemblyseqload.config
MGI_CONFIG=b6_assemblyseqload.config
VISTAREG_CONFIG=vistareg_assemblyseqload.config

ENSEMBL_ASSOCCONFIG=ensembl_assocload.config
NCBI_ASSOCCONFIG=ncbi_assocload.config
ENSEMBLREG_ASSOCCONFIG=ensemblreg_assocload.config
VISTAREG_ASSOCCONFIG=vistareg_assocload.config

COMMON_CONFIG=assembly_common.config

# Make sure common config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# Ensembl Sequence Load
#

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBL_CONFIG} ]
then
    echo "Source ${ENSEMBL_CONFIG}"
    . ${ENSEMBL_CONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBL_CONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl seqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# NCBI Sequence Load
# 

# source common config again
. ${COMMON_CONFIG}

# Make sure ncbi config file exists and source it
if [ -r ${NCBI_CONFIG} ]
then
    echo "Source ${NCBI_CONFIG}"
    . ${NCBI_CONFIG}
else
    echo "Cannot source configuration file: ${NCBI_CONFIG}"
    installFailed
fi

#
# run DLAInstall for  ncbi seqload
#
${DLAINSTALL} ${DEV}

#
# MGP Sequence Load
#

# source common config again
. ${COMMON_CONFIG}

# Make sure mgp config file exists and source it
if [ -r ${MGP_CONFIG} ]
then
    echo "Source ${MGP_CONFIG}"
    . ${MGP_CONFIG}
else
    echo "Cannot source configuration file: ${MGP_CONFIG}"
    installFailed
fi

#
# run DLAInstall for mgp seqload
#
${DLAINSTALL} ${DEV}

# source common config again
. ${COMMON_CONFIG}

# Make sure MGI B6 config file exists and source it
if [ -r ${MGI_CONFIG} ]
then
    echo "Source ${MGI_CONFIG}"
    . ${MGI_CONFIG}
else
    echo "Cannot source configuration file: ${MGI_CONFIG}"
    installFailed
fi

#
# run DLAInstall for b6 seqload
#
${DLAINSTALL} ${DEV}

#
# Ensembl Assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBL_ASSOCCONFIG} ]
then
    echo "Source ${ENSEMBL_ASSOCCONFIG}"
    . ${ENSEMBL_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBL_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl assocload
#
${DLAINSTALL} ${DEV}

#
# NCBI Assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ncbi config file exists and source it
if [ -r ${NCBI_ASSOCCONFIG} ]
then
    echo "Source ${NCBI_ASSOCCONFIG}"
    . ${NCBI_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${NCBI_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ncbi assocload
#
${DLAINSTALL} ${DEV}

#
# Ensembl Reg Sequence Load
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBLREG_CONFIG} ]
then
    echo "Source ${ENSEMBLREG_CONFIG}"
    . ${ENSEMBLREG_CONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBLREG_CONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl seqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Ensembl Assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBLREG_ASSOCCONFIG} ]
then
    echo "Source ${ENSEMBLREG_ASSOCCONFIG}"
    . ${ENSEMBLREG_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBLREG_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl assocload
#
${DLAINSTALL} ${DEV}

#
# VISTA Reg Sequence Load
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${VISTAREG_CONFIG} ]
then
    echo "Source ${VISTAREG_CONFIG}"
    . ${VISTAREG_CONFIG}
else
    echo "Cannot source configuration file: ${VISTAREG_CONFIG}"
    installFailed
fi

#
# run DLAInstall for ncbi assocload
#
${DLAINSTALL} ${DEV}

#
# VISTA Assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${VISTAREG_ASSOCCONFIG} ]
then
    echo "Source ${VISTAREG_ASSOCCONFIG}"
    . ${VISTAREG_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${VISTAREG_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl assocload
#
${DLAINSTALL} ${DEV}

# There is no MGP assocload

chgrp mgi *config

