#!/bin/sh

#
# Installation script for assemblyseqload
#
# 1) cp ensembl_assemblyseqload.config.default ensembl_assemblyseqload.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config file names
ENSEMBL_CONFIG=ensembl_assemblyseqload.config
NCBI_CONFIG=ncbi_assemblyseqload.config 
VEGA_CONFIG=vega_assemblyseqload.config
MGP_CONFIG=mgp_assemblyseqload.config

ENSEMBL_ASSOCCONFIG=ensembl_assocload.config
NCBI_ASSOCCONFIG=ncbi_assocload.config
VEGA_ASSOCCONFIG=vega_assocload.config
MGP_ASSOCCONFIG=mgp_assocload.config

COMMON_CONFIG=assembly_common.config

# Make sure common config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBL_CONFIG} ]
then
    echo "Source ${ENSEMBL_CONFIG}"
    . ${ENSEMBL_CONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBL_CONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl seqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# now do ncbi seqload
# 

# source common config again
. ${COMMON_CONFIG}

# Make sure ncbi config file exists and source it
if [ -r ${NCBI_CONFIG} ]
then
    echo "Source ${NCBI_CONFIG}"
    . ${NCBI_CONFIG}
else
    echo "Cannot source configuration file: ${NCBI_CONFIG}"
    installFailed
fi

#
# run DLAInstall for  ncbi seqload
#
${DLAINSTALL} ${DEV}

#
# now do vega seqload
# 

# source common config again
. ${COMMON_CONFIG}

# Make sure vega config file exists and source it
if [ -r ${VEGA_CONFIG} ]
then
    echo "Source ${VEGA_CONFIG}"
    . ${VEGA_CONFIG}
else
    echo "Cannot source configuration file: ${VEGA_CONFIG}"
    installFailed
fi

#
# run DLAInstall for vega seqload
#
${DLAINSTALL} ${DEV}

#
# now do mgp seqload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure mgp config file exists and source it
if [ -r ${MGP_CONFIG} ]
then
    echo "Source ${MGP_CONFIG}"
    . ${MGP_CONFIG}
else
    echo "Cannot source configuration file: ${MGP_CONFIG}"
    installFailed
fi

#
# run DLAInstall for mgp seqload
#
${DLAINSTALL} ${DEV}

#
# now do ensembl assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ensembl config file exists and source it
if [ -r ${ENSEMBL_ASSOCCONFIG} ]
then
    echo "Source ${ENSEMBL_ASSOCCONFIG}"
    . ${ENSEMBL_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${ENSEMBL_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ensembl assocload
#
${DLAINSTALL} ${DEV}

#
# now do ncbi assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure ncbi config file exists and source it
if [ -r ${NCBI_ASSOCCONFIG} ]
then
    echo "Source ${NCBI_ASSOCCONFIG}"
    . ${NCBI_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${NCBI_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for ncbi assocload
#
${DLAINSTALL} ${DEV}

#
# now do vega assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure vega config file exists and source it
if [ -r ${VEGA_ASSOCCONFIG} ]
then
    echo "Source ${VEGA_ASSOCCONFIG}"
    . ${VEGA_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${VEGA_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for vega assocload
#
${DLAINSTALL} ${DEV}

#
# now do mgp assocload
#

# source common config again
. ${COMMON_CONFIG}

# Make sure mgp config file exists and source it
if [ -r ${MGP_ASSOCCONFIG} ]
then
    echo "Source ${MGP_ASSOCCONFIG}"
    . ${MGP_ASSOCCONFIG}
else
    echo "Cannot source configuration file: ${MGP_ASSOCCONFIG}"
    installFailed
fi

#
# run DLAInstall for mgp assocload
#
${DLAINSTALL} ${DEV}

chgrp mgi *config

